chore: more demonstrative examples
algorandfoundation/algokit-subscriber-py pull request #14
Opened 2024-11-07 21:12 UTC by joe-p

## Proposed Changes

- Makes the examples a bit more realistic and demonstrative of the various ways the subscriber could be used

2024-11-19 18:39 UTC, joe-p commented
@SilentRhetoric I have added you as a reviewer of this PR. The intention is that devrel can use these examples to get an initial understanding of how the library is used asynchronously. Then we can follow-up with a meeting with any questions/feedback if needed.

2025-05-01 13:09 UTC, SilentRhetoric requested changes
Thank you for these examples--very helpful. Just flagged a few nits.

2025-05-01 13:09 UTC, SilentRhetoric commented on examples/governance/governance.py
> +                # Only match non-zero USDC transfers
Update old comment from another example

2025-05-01 13:09 UTC, SilentRhetoric commented on examples/governance/governance.py
> +# Every subscriber instance uses a water to track what block it processed last.
Typo; `water` should be `watermark`

2025-05-01 13:09 UTC, SilentRhetoric commented on examples/live_monitoring/live_monitoring.py
> +# Every subscriber instance uses a water to track what block it processed last.
Typo; `water` should be `watermark`

2025-05-01 13:09 UTC, SilentRhetoric commented on examples/transaction_recording/transaction_recording.py
> +    watermark_file.write_text("43932536")
Should this be 0?

2025-05-07 19:10 UTC, SilentRhetoric approved these changes

2025-05-09 12:38 UTC, joe-p commented
@lempira Can you try running `poetry run pre-commit run --all-files` locally? It's passing for me locally but not on CI for some reason.

2025-05-09 19:59 UTC, lempira commented
> @lempira Can you try running `poetry run pre-commit run --all-files` locally? It's passing for me locally but not on CI for some reason.

There were some ruff files that were failing. I think the ruff version in the ci was different than the one the pyproject. (not sure why, tho) I updated ruff to the latest in a previous commit before the HEAD of this branch. I rebased main and then precommited all files.

2025-05-10 13:53 UTC, lempira approved these changes

2025-05-10 14:00 UTC, merged